config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :texts

end

app/models/text.rb
# == Schema Information
#
# Table name: texts
#
#  id         :integer          not null, primary key
#  post       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Text < ActiveRecord::Base

  URL_PREFIXES = ["http://", "https://"]
  GOOGLE_MAPS_PREFIX = "https://maps.googleapis.com/maps/api/geocode/json?latlng="
  API_KEY = "AIzaSyBQNkbUutzC_u5gbZNFuv87YIl7DySWDLU"

  before_save do
    self.post = parse_input(self.post)
  end

  def parse_input(text)
    items_arr = parse_items(text)
    final_text = []
    items_arr.each {|item| final_text << transform_text(item) }
    final_text.join("")
  end

  def parse_items(text)
    items_arr = []
    chars = text.split("")

    i = 0
    length = 0
    brackets_open = false

    until chars.length == 0 do
      el = chars[i]

      # pulls out anything enclosed in brackets as its own item
      if el == "["
        brackets_open = true
        length += 1
        i += 1
      elsif el == "]"
        brackets_open = false
        items_arr << chars.shift(length + 1).join("")
        length, i = 0, 0
        next
      elsif brackets_open && el != "]"
        length += 1
        i += 1
      elsif !brackets_open && el == " "
        # filters white space as ordered elements with a len of 1
        items_arr << chars.shift(1).join("")
        length, i = 0, 0
        next
      elsif !brackets_open && el != " "
        if length+1 == chars.length || chars[i+1] == " " || chars[i+1] == "["
          items_arr << chars.shift(length + 1).join("")
          length, i = 0, 0
          next
        end
        length += 1
        i += 1
      end
    end
    items_arr
  end

  def transform_text(item)
    if item[0] == "["
      return append_address(item)
    elsif item_is_URL?(item)
      return strip_URL(item)
    elsif item.length == 1
      return item
    elsif item_is_even?(item)
      return item
    else
      return reverse(item)
    end
  end

  def append_address(item)
    latlon = item[1..-2].gsub(/\s+/, "")
    response = HTTParty.get(GOOGLE_MAPS_PREFIX + latlon +'&key=' + API_KEY)
    if response.code == 200
     return item + "(" + JSON.parse(response.body)["results"][0]["formatted_address"] + ")"
    end
    item
  end

  def item_is_URL?(string)
    URL_PREFIXES.any? do |pref|
      len = pref.length
      string[0...len] == pref
    end
  end

  def item_is_even?(item)
    if !("a".."z").to_a.include?(item.last)
      return (item.length - 1).even?
    else
      return item.length.even?
    end
  end

  def reverse(item)
    if !("a".."z").to_a.include?(item.last)
      return item[0..-2].reverse + item[-1]
    else
      return item.reverse
    end
  end

  def strip_URL(item)
    URL_PREFIXES.each do |pref|
      len = pref.length
      if item[0...len] == pref
        return item[len..-1]
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  after_filter :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  private

  def verified_request?
    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: [:show, :edit]

  def index
    render json: Text.all
  end

  def show
    render json: Text.find(params[:id])
  end

  # GET /texts/new
  def new
    @text = Text.new
  end

  # GET /texts/1/edit
  def edit
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(text_params)
    if @text.save!
      render json: @text
    else
      flash.now[:errors] = @text.errors.full_messages
      render json: @text
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_params
      params.require(:text).permit(:post, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grio</title>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application"%>
  <%= stylesheet_link_tag  "application" %>
</head>
<body data-ng-app="grioParser" ng-cloak>

<%= yield %>

</body>
</html>

app/views/static_pages/index.html.erb
<div class="container" ng-controller="appController">
  <h1 class="app-title">{{::title}}</h1>
  <form ng-submit="submitInput()">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <input type="submit" class="button" value="Submit">
    <input placeholder="&nbsp;&nbsp;input goes here" ng-change="updateInput(input)" ng-model="input"><br/>
  </form>
  <div class="inputs-list">
    <ul>
      <li ng-repeat="input in parsedInputs">{{input.post}}</li>
    </ul>
  </div>

</div>

app/views/texts/_form.html.erb
<%= form_for(@text) do |f| %>
  <% if @text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text.errors.count, "error") %> prohibited this text from being saved:</h2>

      <ul>
      <% @text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/texts/edit.html.erb
<h1>Editing Text</h1>

<%= render 'form' %>

<%= link_to 'Show', @text %> |
<%= link_to 'Back', texts_path %>

app/views/texts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Texts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @texts.each do |text| %>
      <tr>
        <td><%= link_to 'Show', text %></td>
        <td><%= link_to 'Edit', edit_text_path(text) %></td>
        <td><%= link_to 'Destroy', text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text', new_text_path %>

app/views/texts/new.html.erb
<h1>New Text</h1>

<%= render 'form' %>

<%= link_to 'Back', texts_path %>

app/views/texts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_text_path(@text) %> |
<%= link_to 'Back', texts_path %>